# popup — build helpers.  Everything runs through `uv run`, so there is nothing to install.
SHELL := /bin/bash
PY    ?= python3
RUN   ?= uv run
# Test deps: pytest (runner), moto[server]+flask (loopback S3 for test_sources — plain
# `moto` has no server mode and the S3 fixture fails), boto3 (popup's own s3:// extra: the
# subprocess under test imports it).  Nothing here touches the network.
TEST_RUN ?= $(RUN) --with pytest --with 'moto[server]' --with flask --with boto3
SMOKE_LOG := .smoke.log
SMOKE_OUT := .smoke.html

.PHONY: help embed lint test smoke coverage clean
.DEFAULT_GOAL := help

help:
	@echo "make embed  — inline shell.html + renderers/fits.js into popup.py"
	@echo "make lint   — ruff + mypy"
	@echo "make test   — pytest (no network; moto for S3)"
	@echo "make smoke  — real cloudflared end-to-end (manual / CI-optional)"

# --- embed -------------------------------------------------------------------
# Rewrites the block between `# --- EMBED:<NAME> ---` and `# --- /EMBED:<NAME> ---`
# in popup.py with `<VAR> = <repr of file contents>`.  chr(35) builds the '#' so make
# does not eat it as a comment inside this variable assignment.
EMBED = $(PY) -c 'import pathlib,re,sys; m,f,v = sys.argv[1:4]; h = chr(35); p = pathlib.Path("popup.py"); s = p.read_text(); pat = re.compile("(?s)(%s --- EMBED:%s ---\n).*?(%s --- /EMBED:%s ---)" % (h, m, h, m)); sys.exit("make embed: missing markers %s --- EMBED:%s --- ... %s --- /EMBED:%s --- in popup.py" % (h, m, h, m)) if not pat.search(s) else None; p.write_text(pat.sub(lambda x: x.group(1) + v + " = " + repr(pathlib.Path(f).read_text()) + "  " + h + " generated by `make embed` — edit " + f + ", not this line\n" + x.group(2), s, count=1)); print("embedded %s -> %s" % (f, v))'

embed:
	$(EMBED) SHELL shell.html SHELL_HTML
	$(EMBED) FITS renderers/fits.js FITS_JS
	@$(PY) -c 'import ast; ast.parse(open("popup.py").read()); print("popup.py still parses")'

# --- quality -----------------------------------------------------------------
lint:
	$(RUN) --with ruff ruff check popup.py tests
	$(RUN) --with mypy --with pytest mypy popup.py

test:
	$(TEST_RUN) pytest tests -q

# --- smoke (needs cloudflared + real network) --------------------------------
# Note: the page title is rendered client-side, so curl cannot see it.  We assert the
# next best server-observable thing: HTTP 200, the shell was served, and the
# __POPUP_CONFIG__ token was replaced with real JSON.
smoke:
	@rm -f $(SMOKE_LOG) $(SMOKE_OUT)
	@command -v cloudflared >/dev/null || { echo "smoke: cloudflared not on PATH"; exit 1; }
	@$(RUN) popup.py README.md --ttl 2m --no-qr --no-password >$(SMOKE_LOG) 2>&1 & echo $$! >.smoke.pid; \
	for i in $$(seq 1 60); do grep -qo 'https://[a-z0-9-]*\.trycloudflare\.com' $(SMOKE_LOG) && break; sleep 1; done; \
	url=$$(grep -o 'https://[a-z0-9-]*\.trycloudflare\.com' $(SMOKE_LOG) | head -1); \
	rc=0; \
	if [ -z "$$url" ]; then echo "smoke: no tunnel URL in $(SMOKE_LOG)"; rc=1; else \
	  code=$$(curl -sS --max-time 30 -o $(SMOKE_OUT) -w '%{http_code}' "$$url"); \
	  [ "$$code" = 200 ] || { echo "smoke: HTTP $$code from $$url"; rc=1; }; \
	  grep -q 'window.POPUP' $(SMOKE_OUT) || { echo "smoke: renderer shell not served"; rc=1; }; \
	  grep -q '__POPUP_CONFIG__' $(SMOKE_OUT) && { echo "smoke: config token was not replaced"; rc=1; }; \
	  grep -q '"name": *"README.md"' $(SMOKE_OUT) || grep -q '"name":"README.md"' $(SMOKE_OUT) || { echo "smoke: injected config does not name README.md"; rc=1; }; \
	  [ $$rc = 0 ] && echo "smoke OK: $$url"; \
	fi; \
	kill $$(cat .smoke.pid) 2>/dev/null; rm -f .smoke.pid; exit $$rc

clean:
	rm -rf $(SMOKE_LOG) $(SMOKE_OUT) .smoke.pid .coverage .pytest_cache .mypy_cache .ruff_cache \
	       tests/__pycache__ __pycache__

# Repeatable coverage of popup.py itself. The suite drives popup.py as a subprocess,
# so plain --cov sees nothing; this installs coverage's subprocess hook instead.
COVDIR := .covhook
coverage:
	@rm -rf $(COVDIR) && mkdir -p $(COVDIR)
	@printf '[run]\nparallel = true\ninclude = $(CURDIR)/popup.py\ndata_file = $(CURDIR)/$(COVDIR)/covdata\n' > $(COVDIR)/.coveragerc
	@printf 'import coverage; coverage.process_startup()\n' > $(COVDIR)/sitecustomize.py
	PYTHONPATH=$(CURDIR)/$(COVDIR) COVERAGE_PROCESS_START=$(CURDIR)/$(COVDIR)/.coveragerc $(TEST_RUN) --with coverage pytest tests -q
	@$(RUN) --with coverage coverage combine --rcfile=$(COVDIR)/.coveragerc > /dev/null
	@$(RUN) --with coverage coverage report --rcfile=$(COVDIR)/.coveragerc

